---
title: "Introduction to Bayesian Statistics"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
    css: css/learnr-theme.css
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
if ("learnr" %in% (.packages()))
  detach(package:learnr, unload = TRUE)
library(learnr)
knitr::opts_chunk$set(echo = FALSE)

## Save package names as a vector of strings
pkgs <-  c()

## Install uninstalled packages
lapply(pkgs[!(pkgs %in% installed.packages())], 
       install.packages,
       repos='http://cran.us.r-project.org')

## Load all packages to library and adjust options
lapply(pkgs, library, character.only = TRUE)
```

## Introductions

### Hi, I'm Denis

- Senior Research Fellow, Data and Methods Unit, MZES
- Dr. phil. (political science), Humboldt University of Berlin (2018)


### Here are some of the things I (have) work(ed) on:

#### The political economy of spatial inequalities

- *Rental market risk and radical right support* (with Tarik Abou-Chadi and Thomas Kurer)
- *Preferences for rent control: Between political geography and political economy* [`brms`]
- *The housing crisis on social media: Housing markets and the subnational diversification of policy supply* (with Tim Allinger and Andreas Küpfer) [`rstan`]

#### Far-right voting

- *Between strategy and protest: How policy demand, political dissatisfaction and strategic incentives matter for far-right voting* [`rstan`]
- *Ökonomisches Risiko und die elektorale Anziehungskraft der AfD*
- *Economic Risk, Anti-Immigration Preferences and Voting for the Radical Right* [`rstan`]

#### Party competition

- *The Centre-Right versus the Radical Right: the Role of Migration Issues and Economic Grievances* (with Tarik Abou-Chadi and Markus Wagner)
- *Does Accommodation Work? Mainstream Party Strategies and the Success of Radical Right Parties* (with Werner Krause and Tarik Abou-Chadi)
- *Comparative voteswitching: A new framework for studying dynamic multiparty competition* (with Werner Krause and Tarik Abou-Chadi) [`rstan`]


#### Methods

- [*Methods Bites: Blog of the MZES Social Science Data Lab*](https://www.mzes.uni-mannheim.de/socialsciencedatalab/) (with Cosima Meyer and Julian Bernauer)
- *Simulating party shares* (with Chris Hanretty) [`cmdstanr`]
- *Triangular visualizations: Making sense of statistical significance in multi-group comparisons*

### Who are you, and what brought you here?

## Introduction to Bayesian Statistics

###  Learning Objectives

1. Contrast frequentist and Bayesian inference paradigms
1. Understand when and why researchers go Bayesian
1. Understand the basics of analytical and (especially) numerical Bayesian inference
1. Understand the costs and benefits of doing applied Bayesian data analysis
1. Perform applied Bayesian data analysis using the R package `brms` (Bayesian Regression Models using 'Stan')

### The end goal

Empower you to 

- implement
- execute 
- process
- scrutinize
- understand

Bayesian data analysis using pre-implemented tools.

## Schedule

### Sessions

| Session | Session          | Topics                                                                             |
| :-----: | ---------------: | :----------------------------------------------------------------------------------|
|    1.1  | Wed, 09:00-10:30 | *Lecture:* **R and Frequentist Inference: A Refresher**                            |
|    1.2  |      10:45-12:15 | *Lecture:* **Bayesian Fundamentals**                                               |
|    1.3  |      13:45-15:15 | **Lab session Day 1**                                                              |
|    2.1  | Thu, 09:00-10:30 | *Lecture:***Applied Bayesian Statistics I: Basics & Workflow**                     |
|    2.2  |      10:45-12:15 | *Lecture:***Applied Bayesian Statistics II: Using brms**                           |
|    2.3  |      13:45-15:15 | **Lab session: Exercises and solutions**                                           |
|    3.1  | Fri, 09:00-10:30 | **Applied Bayesian Statistics III: Implementing a small data project using brms**  |    
|    3.2  |      10:45-12:15 | **Wrap-up**                                                                        |
|         |                  | - Review of challenges and potentials encountered in working on your data projects |
|         |                  | - Outlook: Moving forward as Bayesian practitioners                                |
|         |                  | - Course evaluations and feedback                                                  |

### Structure of our sessions

1. Lecture:
    - Input
    - Dedicated Q&A (but feel free to ask for clarification at any point!)
    - Little interactive data exercises (so please click along!)
2. Lab: Hands-on exercises (in small teams), solutions to exercises
    - You will be assigned to small teams in breakout rooms
    - I will be in the main meeting, available for questions
    - Tim will switch between breakout rooms to assist you

### Session 3.1: Implementing a small data project using brms

- Becoming an active Bayesian practitioner and/or model developer requires practice!
- The challenges you may encounter along the way will likely be idiosyncratic
- Therefore, Session 3.1 gives you the chance to implement the Bayesian workflow using your own data
- This can be an analysis you are about to run for the first time or a replication of your existing work,as long as:
    - Pre-processing is complete: Your data is ready to go for data analysis
    - Neither your data nor your model are highly complex (if they are: start with a small subset of the data, gradually build up model complexity)
- I will be available for questions throughout Session 3.1
- We will jointly discuss your experiences and the main challenges you encountered at the start of Session 3.2

### RStan/brms installation: Any problems?

Did you successfully got RStan to run on your machine, incl. `example(stan_model, package = "rstan", run.dontrun = TRUE) `?

- If yes: Great! You're all set!
- If no: No worries, we will start using these softwares *tomorrow*. I will stick around after 15:15 today in case you need assistance.

## Questions?




